name: ci

on:
  push:

jobs:
  docker:
    runs-on: linux/arm64
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: qdw1010
          password: dckr_pat_Ts7FF5re9IFqHYce7Ln3DzaEzgQ
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: 
           qdw1010/aggregator:20240727001
