name: checkin
on:
  schedule:
    - cron: "45 02 * * *"
  workflow_dispatch: # 允许手动触发

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: auto checkin for traffic

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - run: |
          cd .github
          python actions/checkin/universal.py

      - name: timestamp
        run: date
